### ISSUE TITLE
NumPy article

### ISSUE THREAD

**Issue by Parcly-Taxel** [se-edu/learningresources#167]
_"The fundamental package for scientific computing with Python" – NumPy itself_

_Assumptions_: The reader has basic knowledge of Python and its lists.

* Why NumPy?
* The array object
  * Axes
* Broadcasting
* Functions available in NumPy's standard library
* NumPy's dependents
* Tutorials

**Comment by damithc** [comment]
Let's keep in short (because not exactly an SE topic). Also, let's not write it as if you are trying to teach NumPy (e.g., no need to explain how to install). Instead, make the reader aware of NumPy and what it can do, help reader decide if NumPy is a match for their needs, and point where to go if they wanted to actually learn and use it.
